STATUS_CODE_GROUPS = {'1xx': {'title': {'nl': 'Informatief', 'en': 'Informational', 'zh': '信息', 'es': 'Informativo', 'ar': 'معلوماتي', 'ru': 'Информационный'},
         'description': {'nl': '1xx-statuscodes geven aan dat de server het verzoek heeft ontvangen en dat de '
                               'verwerking wordt voortgezet.',
                         'en': '1xx status codes indicate that the server has received the request and that processing is continuing.',
                         'zh': '1xx状态码表示服务器已收到请求，处理仍在继续。',
                         'es': 'Los códigos de estado 1xx indican que el servidor ha recibido la solicitud y que el procesamiento continúa.',
                         'ar': 'تشير رموز الحالة 1xx إلى أن الخادم استقبل الطلب وأن المعالجة لا تزال جارية.',
                         'ru': 'Коды состояния 1xx означают, что сервер получил запрос и обработка продолжается.'}},
 '2xx': {'title': {'nl': 'Aanvraag succesvol', 'en': 'Successful request', 'zh': '请求成功', 'es': 'Solicitud exitosa', 'ar': 'طلب ناجح', 'ru': 'Успешный запрос'},
         'description': {'nl': 'Het verzoek is ontvangen, begrepen en succesvol verwerkt.',
                         'en': 'The request was received, understood, and successfully processed.',
                         'zh': '请求已被接收、理解并成功处理。',
                         'es': 'La solicitud fue recibida, entendida y procesada correctamente.',
                         'ar': 'تم استلام الطلب وفهمه ومعالجته بنجاح.',
                         'ru': 'Запрос был получен, понят и успешно обработан.'},
         'google_note': {'nl': 'Bij de meeste 2xx-codes kunnen pagina\'s worden geïndexeerd. 204 wordt vaak behandeld '
                               'als een zachte 404.',
                         'en': 'Most 2xx responses can be indexed. 204 is often treated as a soft 404.',
                         'zh': '大多数2xx响应可以被索引。204通常被视为软404。',
                         'es': 'La mayoría de las respuestas 2xx pueden indexarse. El 204 suele tratarse como un 404 suave.',
                         'ar': 'يمكن فهرسة معظم استجابات 2xx. غالبًا ما يُعامل 204 كـ 404 ناعم.',
                         'ru': 'Большинство ответов 2xx могут быть проиндексированы. 204 часто воспринимается как мягкий 404.'}},
 '3xx': {'title': {'nl': 'Omleidingen', 'en': 'Redirects', 'zh': '重定向', 'es': 'Redirecciones', 'ar': 'إعادة التوجيه', 'ru': 'Перенаправления'},
         'description': {'nl': 'Er is extra actie nodig, meestal een redirect naar een andere URL.',
                         'en': 'Extra action is needed, usually a redirect to another URL.',
                         'zh': '需要额外操作，通常是重定向到另一个URL。',
                         'es': 'Se requiere una acción adicional, generalmente una redirección a otra URL.',
                         'ar': 'يلزم اتخاذ إجراء إضافي، عادةً إعادة التوجيه إلى عنوان URL آخر.',
                         'ru': 'Требуется дополнительное действие, обычно перенаправление на другой URL.'},
         'google_note': {'nl': '301 en 302 zijn belangrijke signalen voor Google. Redirect-ketens moeten zo kort '
                               'mogelijk blijven.',
                         'en': '301 and 302 are important signals for Google. Redirect chains should be kept as short '
                               'as possible.',
                         'zh': '301和302是Google的重要信号。重定向链应尽量缩短。',
                         'es': '301 y 302 son señales importantes para Google. Las cadenas de redirección deben mantenerse lo más cortas posible.',
                         'ar': '301 و302 إشارات مهمة لـ Google. يجب أن تكون سلاسل إعادة التوجيه قصيرة قدر الإمكان.',
                         'ru': '301 и 302 — важные сигналы для Google. Цепочки перенаправлений должны быть как можно короче.'}},
 '4xx': {'title': {'nl': 'Clientfouten', 'en': 'Client errors', 'zh': '客户端错误', 'es': 'Errores del cliente', 'ar': 'أخطاء العميل', 'ru': 'Ошибки клиента'},
         'description': {'nl': 'Het verzoek van de client bevat een fout of kan niet worden uitgevoerd.',
                         'en': 'The client request contains an error or cannot be fulfilled.',
                         'zh': '客户端请求包含错误或无法完成。',
                         'es': 'La solicitud del cliente contiene un error o no puede completarse.',
                         'ar': 'يحتوي طلب العميل على خطأ أو لا يمكن تنفيذه.',
                         'ru': 'Запрос клиента содержит ошибку или не может быть выполнен.'},
         'google_note': {'nl': '4xx-codes kunnen ervoor zorgen dat pagina\'s uit de index verdwijnen.',
                         'en': '4xx responses may cause pages to disappear from the index.',
                         'zh': '4xx响应可能导致页面从索引中消失。',
                         'es': 'Las respuestas 4xx pueden hacer que las páginas desaparezcan del índice.',
                         'ar': 'قد تتسبب استجابات 4xx في اختفاء الصفحات من الفهرس.',
                         'ru': 'Ответы 4xx могут привести к исчезновению страниц из индекса.'}},
 '5xx': {'title': {'nl': 'Serverfouten', 'en': 'Server errors', 'zh': '服务器错误', 'es': 'Errores del servidor', 'ar': 'أخطاء الخادم', 'ru': 'Ошибки сервера'},
         'description': {'nl': 'De server heeft een fout en kan het verzoek niet goed afhandelen.',
                         'en': 'The server has encountered an error and cannot properly handle the request.',
                         'zh': '服务器遇到错误，无法正常处理请求。',
                         'es': 'El servidor ha encontrado un error y no puede gestionar la solicitud correctamente.',
                         'ar': 'واجه الخادم خطأً ولا يمكنه معالجة الطلب بشكل صحيح.',
                         'ru': 'Сервер столкнулся с ошибкой и не может надлежащим образом обработать запрос.'},
         'google_note': {'nl': '5xx-fouten vertragen crawlen en kunnen uiteindelijk indexatieproblemen geven.',
                         'en': '5xx errors slow down crawling and may eventually cause indexing issues.',
                         'zh': '5xx错误会减慢爬取速度，最终可能导致索引问题。',
                         'es': 'Los errores 5xx ralentizan el rastreo y pueden causar problemas de indexación.',
                         'ar': 'تؤدي أخطاء 5xx إلى إبطاء الزحف وقد تتسبب في نهاية المطاف في مشاكل الفهرسة.',
                         'ru': '5xx ошибки замедляют сканирование и со временем могут вызвать проблемы с индексацией.'}}}

STATUS_CODES = {'100': {'group': '1xx',
         'title': {'nl': 'Ga verder', 'en': 'Continue', 'zh': '继续', 'es': 'Continuar', 'ar': 'استمر', 'ru': 'Продолжить'},
         'meaning': {'nl': 'Alles is nu in orde. Blijf doorgaan.', 'en': 'Everything is fine so far. Keep going.', 'zh': '目前一切正常，请继续。', 'es': 'Todo está bien hasta ahora. Continúa.', 'ar': 'كل شيء على ما يرام حتى الآن. استمر.', 'ru': 'Всё в порядке. Продолжайте.'}},
 '101': {'group': '1xx',
         'title': {'nl': 'Van protocol wisselen', 'en': 'Switching Protocols', 'zh': '切换协议', 'es': 'Cambio de protocolo', 'ar': 'تبديل البروتوكول', 'ru': 'Смена протокола'},
         'meaning': {'nl': 'Er is een bericht dat wisselt naar een ander protocol.',
                     'en': 'The server is switching to a different protocol as requested.',
                     'zh': '服务器正在按请求切换到不同的协议。',
                     'es': 'El servidor está cambiando a un protocolo diferente según lo solicitado.',
                     'ar': 'يقوم الخادم بالتبديل إلى بروتوكول مختلف كما طُلب.',
                     'ru': 'Сервер переключается на другой протокол по запросу клиента.'}},
 '102': {'group': '1xx',
         'title': {'nl': 'Verwerking', 'en': 'Processing', 'zh': '处理中', 'es': 'Procesando', 'ar': 'قيد المعالجة', 'ru': 'Обработка'},
         'meaning': {'nl': 'Dingen gebeuren, maar zijn nog niet klaar.',
                     'en': 'Things are happening, but are not yet complete.',
                     'zh': '正在处理，但尚未完成。',
                     'es': 'Las cosas están sucediendo, pero aún no están completas.',
                     'ar': 'الأمور تجري، لكنها لم تكتمل بعد.',
                     'ru': 'Обработка идёт, но ещё не завершена.'}},
 '103': {'group': '1xx',
         'title': {'nl': 'Vroege tips', 'en': 'Early Hints', 'zh': '早期提示', 'es': 'Sugerencias tempranas', 'ar': 'تلميحات مبكرة', 'ru': 'Ранние подсказки'},
         'meaning': {'nl': 'Helpt bronnen vooraf laden, wat Largest Contentful Paint kan verbeteren.',
                     'en': 'Helps preload resources, which can improve Largest Contentful Paint.',
                     'zh': '帮助预加载资源，可以改善最大内容绘制（LCP）。',
                     'es': 'Ayuda a precargar recursos, lo que puede mejorar el Largest Contentful Paint.',
                     'ar': 'يساعد على التحميل المسبق للموارد، مما قد يحسّن أكبر عرض للمحتوى.',
                     'ru': 'Помогает предварительно загружать ресурсы, что может улучшить Largest Contentful Paint.'}},
 '200': {'group': '2xx',
         'title': {'nl': 'OK', 'en': 'OK', 'zh': '成功', 'es': 'OK', 'ar': 'ناجح', 'ru': 'OK'},
         'meaning': {'nl': 'Het verzoek is succesvol verwerkt.', 'en': 'The request was successfully processed.', 'zh': '请求已成功处理。', 'es': 'La solicitud se procesó correctamente.', 'ar': 'تمت معالجة الطلب بنجاح.', 'ru': 'Запрос успешно обработан.'},
         'testing_tips': {'nl': ['Controleer of de juiste content wordt weergegeven.',
                                 'Test of alle onderdelen van de pagina correct laden (afbeeldingen, scripts).',
                                 'Kijk of de inhoud overeenkomt met de verwachting van de gebruiker.',
                                 'Controleer of er geen verborgen fouten optreden ondanks de 200-status.'],
                          'en': ['Check whether the correct content is displayed.',
                                 'Test whether all parts of the page load correctly (images, scripts).',
                                 'Verify that the content matches the user\'s expectations.',
                                 'Check whether hidden errors occur despite the 200 status.'],
                          'zh': ['检查是否显示了正确的内容。',
                                 '测试页面的所有部分（图片、脚本）是否正确加载。',
                                 '验证内容是否符合用户的预期。',
                                 '检查尽管状态为200，是否存在隐藏错误。'],
                          'es': ['Comprueba si se muestra el contenido correcto.',
                                 'Verifica que todas las partes de la página cargan correctamente (imágenes, scripts).',
                                 'Confirma que el contenido coincide con las expectativas del usuario.',
                                 'Comprueba si se producen errores ocultos a pesar del estado 200.'],
                          'ar': ['تحقق من عرض المحتوى الصحيح.',
                                 'اختبر تحميل جميع أجزاء الصفحة بشكل صحيح (الصور والسكريبتات).',
                                 'تحقق من أن المحتوى يطابق توقعات المستخدم.',
                                 'تحقق من عدم وجود أخطاء خفية رغم حالة 200.'],
                          'ru': ['Проверьте, отображается ли правильный контент.',
                                 'Протестируйте корректную загрузку всех элементов страницы (изображения, скрипты).',
                                 'Убедитесь, что контент соответствует ожиданиям пользователя.',
                                 'Проверьте, нет ли скрытых ошибок, несмотря на статус 200.']}},
 '201': {'group': '2xx',
         'title': {'nl': 'Gemaakt', 'en': 'Created', 'zh': '已创建', 'es': 'Creado', 'ar': 'تم الإنشاء', 'ru': 'Создано'},
         'meaning': {'nl': 'Succes, en er is een nieuwe resource aangemaakt.',
                     'en': 'Success, and a new resource has been created.',
                     'zh': '成功，并已创建新资源。',
                     'es': 'Éxito, y se ha creado un nuevo recurso.',
                     'ar': 'نجاح، وتم إنشاء مورد جديد.',
                     'ru': 'Успех, и был создан новый ресурс.'}},
 '202': {'group': '2xx',
         'title': {'nl': 'Geaccepteerd', 'en': 'Accepted', 'zh': '已接受', 'es': 'Aceptado', 'ar': 'مقبول', 'ru': 'Принято'},
         'meaning': {'nl': 'Aanvraag is geaccepteerd, maar nog niet voltooid.',
                     'en': 'The request has been accepted but not yet completed.',
                     'zh': '请求已被接受，但尚未完成。',
                     'es': 'La solicitud ha sido aceptada pero aún no completada.',
                     'ar': 'تم قبول الطلب لكنه لم يكتمل بعد.',
                     'ru': 'Запрос принят, но ещё не завершён.'}},
 '203': {'group': '2xx',
         'title': {'nl': 'Niet-bevoegde informatie', 'en': 'Non-Authoritative Information', 'zh': '非权威信息', 'es': 'Información no autoritativa', 'ar': 'معلومات غير موثوقة', 'ru': 'Не авторитетная информация'},
         'meaning': {'nl': 'Er is iets veranderd nadat het van de server naar je is verzonden.',
                     'en': 'Something changed after it was sent from the server to you.',
                     'zh': '内容在从服务器发送到您之后发生了变化。',
                     'es': 'Algo cambió después de que fue enviado desde el servidor.',
                     'ar': 'تغيّر شيء ما بعد إرساله من الخادم إليك.',
                     'ru': 'Что-то изменилось после того, как было отправлено с сервера.'}},
 '204': {'group': '2xx',
         'title': {'nl': 'Geen inhoud', 'en': 'No Content', 'zh': '无内容', 'es': 'Sin contenido', 'ar': 'لا يوجد محتوى', 'ru': 'Нет содержимого'},
         'meaning': {'nl': 'Het verzoek is gelukt, maar er is geen inhoud in de body.',
                     'en': 'The request succeeded, but there is no content in the response body.',
                     'zh': '请求成功，但响应正文中没有内容。',
                     'es': 'La solicitud tuvo éxito, pero no hay contenido en el cuerpo de respuesta.',
                     'ar': 'نجح الطلب، لكن لا يوجد محتوى في جسم الاستجابة.',
                     'ru': 'Запрос выполнен успешно, но тело ответа не содержит данных.'}},
 '205': {'group': '2xx',
         'title': {'nl': 'Inhoud resetten', 'en': 'Reset Content', 'zh': '重置内容', 'es': 'Restablecer contenido', 'ar': 'إعادة تعيين المحتوى', 'ru': 'Сбросить содержимое'},
         'meaning': {'nl': 'Zet het document terug in de oorspronkelijke staat, bijvoorbeeld door een formulier te '
                           'wissen.',
                     'en': 'Reset the document to its original state, for example by clearing a form.',
                     'zh': '将文档重置为原始状态，例如清除表单。',
                     'es': 'Restablece el documento a su estado original, por ejemplo borrando un formulario.',
                     'ar': 'إعادة المستند إلى حالته الأصلية، مثلاً عن طريق مسح نموذج.',
                     'ru': 'Сбросить документ в исходное состояние, например очистить форму.'}},
 '206': {'group': '2xx',
         'title': {'nl': 'Gedeeltelijke inhoud', 'en': 'Partial Content', 'zh': '部分内容', 'es': 'Contenido parcial', 'ar': 'محتوى جزئي', 'ru': 'Частичное содержимое'},
         'meaning': {'nl': 'Slechts een deel van de inhoud is verzonden.',
                     'en': 'Only part of the content has been sent.',
                     'zh': '只发送了部分内容。',
                     'es': 'Solo se ha enviado parte del contenido.',
                     'ar': 'تم إرسال جزء فقط من المحتوى.',
                     'ru': 'Отправлена только часть содержимого.'}},
 '207': {'group': '2xx',
         'title': {'nl': 'Multi-status', 'en': 'Multi-Status', 'zh': '多状态', 'es': 'Multi-estado', 'ar': 'حالات متعددة', 'ru': 'Мультистатус'},
         'meaning': {'nl': 'Er zijn meer responscodes die 2xx, 3xx, 4xx of 5xx kunnen zijn.',
                     'en': 'There are multiple response codes, which may be 2xx, 3xx, 4xx, or 5xx.',
                     'zh': '存在多个响应码，可能是2xx、3xx、4xx或5xx。',
                     'es': 'Hay múltiples códigos de respuesta, que pueden ser 2xx, 3xx, 4xx o 5xx.',
                     'ar': 'توجد رموز استجابة متعددة يمكن أن تكون 2xx أو 3xx أو 4xx أو 5xx.',
                     'ru': 'Существует несколько кодов ответа, которые могут быть 2xx, 3xx, 4xx или 5xx.'}},
 '208': {'group': '2xx',
         'title': {'nl': 'Reeds gerapporteerd', 'en': 'Already Reported', 'zh': '已报告', 'es': 'Ya reportado', 'ar': 'تم الإبلاغ مسبقًا', 'ru': 'Уже сообщено'},
         'meaning': {'nl': 'De client vertelt de server dat dezelfde resource eerder is genoemd.',
                     'en': 'The client tells the server that the same resource has already been mentioned.',
                     'zh': '客户端告诉服务器相同的资源之前已经提到过。',
                     'es': 'El cliente indica al servidor que el mismo recurso ya fue mencionado anteriormente.',
                     'ar': 'يخبر العميل الخادم بأن المورد نفسه تم ذكره من قبل.',
                     'ru': 'Клиент сообщает серверу, что тот же ресурс уже упоминался ранее.'}},
 '218': {'group': '2xx',
         'title': {'nl': 'Dit is prima', 'en': 'This is fine', 'zh': '这没问题', 'es': 'Esto está bien', 'ar': 'هذا جيد', 'ru': 'Всё нормально'},
         'meaning': {'nl': 'Onofficieel gebruik door Apache.', 'en': 'Unofficial use by Apache.', 'zh': 'Apache的非官方用法。', 'es': 'Uso no oficial por Apache.', 'ar': 'استخدام غير رسمي من قِبل Apache.', 'ru': 'Неофициальное использование Apache.'}},
 '226': {'group': '2xx',
         'title': {'nl': 'IM gebruikt', 'en': 'IM Used', 'zh': 'IM已使用', 'es': 'IM utilizado', 'ar': 'تم استخدام IM', 'ru': 'IM использован'},
         'meaning': {'nl': 'De server kan wijzigingen (diffs) van resources verzenden.',
                     'en': 'The server can send changes (diffs) of resources.',
                     'zh': '服务器可以发送资源的变更（差异）。',
                     'es': 'El servidor puede enviar cambios (diffs) de recursos.',
                     'ar': 'يمكن للخادم إرسال التغييرات (الفروق) للموارد.',
                     'ru': 'Сервер может отправлять изменения (патчи) ресурсов.'}},
 '300': {'group': '3xx',
         'title': {'nl': 'Multiple Choices', 'en': 'Multiple Choices', 'zh': '多种选择', 'es': 'Múltiples opciones', 'ar': 'خيارات متعددة', 'ru': 'Множественный выбор'},
         'meaning': {'nl': 'Er is meer dan één mogelijk antwoord.', 'en': 'There is more than one possible response.', 'zh': '有多个可能的响应。', 'es': 'Hay más de una respuesta posible.', 'ar': 'توجد أكثر من إجابة محتملة واحدة.', 'ru': 'Существует более одного возможного ответа.'}},
 '301': {'group': '3xx',
         'title': {'nl': 'Permanent verplaatst', 'en': 'Moved Permanently', 'zh': '永久移动', 'es': 'Movido permanentemente', 'ar': 'نُقل بشكل دائم', 'ru': 'Перемещено навсегда'},
         'meaning': {'nl': 'De oude resource wordt permanent omgeleid naar de nieuwe.',
                     'en': 'The old resource is permanently redirected to the new one.',
                     'zh': '旧资源已被永久重定向到新资源。',
                     'es': 'El recurso antiguo se redirige de forma permanente al nuevo.',
                     'ar': 'تتم إعادة توجيه المورد القديم بشكل دائم إلى الجديد.',
                     'ru': 'Старый ресурс постоянно перенаправлен на новый.'},
         'testing_tips': {'nl': ['Controleer of de redirect direct naar de juiste nieuwe URL gaat.',
                                 'Kijk of er geen onnodige redirect-keten ontstaat.',
                                 'Test of oude links nog goed werken.',
                                 'Controleer of de nieuwe pagina inhoudelijk past bij de oude URL.'],
                          'en': ['Check whether the redirect goes directly to the correct new URL.',
                                 'Verify that no unnecessary redirect chain is created.',
                                 'Test whether old links still work correctly.',
                                 'Check whether the new page content matches the intent of the old URL.'],
                          'zh': ['检查重定向是否直接指向正确的新URL。',
                                 '验证没有创建不必要的重定向链。',
                                 '测试旧链接是否仍然正常工作。',
                                 '检查新页面内容是否符合旧URL的意图。'],
                          'es': ['Comprueba si la redirección va directamente a la nueva URL correcta.',
                                 'Verifica que no se cree una cadena de redirección innecesaria.',
                                 'Prueba si los enlaces antiguos siguen funcionando correctamente.',
                                 'Comprueba si el contenido de la nueva página coincide con la intención de la URL antigua.'],
                          'ar': ['تحقق من أن إعادة التوجيه تذهب مباشرة إلى عنوان URL الجديد الصحيح.',
                                 'تأكد من عدم إنشاء سلسلة إعادة توجيه غير ضرورية.',
                                 'اختبر ما إذا كانت الروابط القديمة لا تزال تعمل بشكل صحيح.',
                                 'تحقق من أن محتوى الصفحة الجديدة يتطابق مع غرض عنوان URL القديم.'],
                          'ru': ['Проверьте, что перенаправление ведёт прямо на правильный новый URL.',
                                 'Убедитесь, что не создаётся ненужная цепочка перенаправлений.',
                                 'Проверьте, работают ли старые ссылки корректно.',
                                 'Убедитесь, что содержимое новой страницы соответствует смыслу старого URL.']}},
 '302': {'group': '3xx',
         'title': {'nl': 'Tijdelijk verplaatst', 'en': 'Found (Temporary Redirect)', 'zh': '临时移动', 'es': 'Encontrado (redirección temporal)', 'ar': 'موجود (إعادة توجيه مؤقتة)', 'ru': 'Найдено (временное перенаправление)'},
         'meaning': {'nl': 'De resource wordt tijdelijk omgeleid naar een andere URL.',
                     'en': 'The resource is temporarily redirected to another URL.',
                     'zh': '资源被临时重定向到另一个URL。',
                     'es': 'El recurso se redirige temporalmente a otra URL.',
                     'ar': 'تتم إعادة توجيه المورد مؤقتًا إلى عنوان URL آخر.',
                     'ru': 'Ресурс временно перенаправлен на другой URL.'},
         'testing_tips': {'nl': ['Controleer of de redirect echt tijdelijk bedoeld is.',
                                 'Test of gebruikers nog op de juiste plek terechtkomen.',
                                 'Controleer of sessies en formulieren correct blijven werken.',
                                 'Kijk of de oorspronkelijke URL later weer actief wordt.'],
                          'en': ['Check whether the redirect is genuinely intended to be temporary.',
                                 'Test whether users still end up in the right place.',
                                 'Check whether sessions and forms continue to work correctly.',
                                 'Verify whether the original URL becomes active again later.'],
                          'zh': ['检查重定向是否真的是临时的。',
                                 '测试用户是否仍然到达正确的位置。',
                                 '检查会话和表单是否继续正常工作。',
                                 '验证原始URL是否会在以后重新变为活动状态。'],
                          'es': ['Comprueba si la redirección es verdaderamente temporal.',
                                 'Prueba si los usuarios siguen llegando al lugar correcto.',
                                 'Verifica si las sesiones y formularios siguen funcionando correctamente.',
                                 'Comprueba si la URL original vuelve a estar activa más adelante.'],
                          'ar': ['تحقق مما إذا كانت إعادة التوجيه مؤقتة فعلًا.',
                                 'اختبر ما إذا كان المستخدمون لا يزالون يصلون إلى المكان الصحيح.',
                                 'تحقق من استمرار عمل الجلسات والنماذج بشكل صحيح.',
                                 'تحقق مما إذا كان عنوان URL الأصلي سيعود نشطًا لاحقًا.'],
                          'ru': ['Проверьте, действительно ли перенаправление является временным.',
                                 'Убедитесь, что пользователи попадают в нужное место.',
                                 'Проверьте корректную работу сессий и форм.',
                                 'Убедитесь, что исходный URL снова станет активным позднее.']}},
 '303': {'group': '3xx',
         'title': {'nl': 'Zie Overige', 'en': 'See Other', 'zh': '查看其他', 'es': 'Ver otro', 'ar': 'انظر إلى غيره', 'ru': 'Смотреть другое'},
         'meaning': {'nl': 'Een andere omleiding die aangeeft dat de resource ergens anders te vinden is.',
                     'en': 'Another redirect indicating that the resource can be found elsewhere.',
                     'zh': '另一种重定向，表示可以在其他地方找到该资源。',
                     'es': 'Otra redirección que indica que el recurso puede encontrarse en otro lugar.',
                     'ar': 'إعادة توجيه أخرى تشير إلى أن المورد موجود في مكان آخر.',
                     'ru': 'Другое перенаправление, указывающее, что ресурс можно найти в другом месте.'}},
 '304': {'group': '3xx',
         'title': {'nl': 'Not Modified', 'en': 'Not Modified', 'zh': '未修改', 'es': 'No modificado', 'ar': 'لم يتم التعديل', 'ru': 'Не изменено'},
         'meaning': {'nl': 'Geeft aan dat de pagina niet is gewijzigd. Meestal gebruikt voor caching.',
                     'en': 'Indicates that the page has not changed. Usually used for caching.',
                     'zh': '表示页面未更改，通常用于缓存。',
                     'es': 'Indica que la página no ha cambiado. Generalmente se usa para caché.',
                     'ar': 'يشير إلى أن الصفحة لم تتغير. يُستخدم عادةً للتخزين المؤقت.',
                     'ru': 'Указывает, что страница не изменилась. Обычно используется для кэширования.'}},
 '305': {'group': '3xx',
         'title': {'nl': 'Proxy gebruiken', 'en': 'Use Proxy', 'zh': '使用代理', 'es': 'Usar proxy', 'ar': 'استخدم وكيلًا', 'ru': 'Использовать прокси'},
         'meaning': {'nl': 'De gevraagde resource is alleen beschikbaar via een proxy.',
                     'en': 'The requested resource is only available through a proxy.',
                     'zh': '请求的资源只能通过代理访问。',
                     'es': 'El recurso solicitado solo está disponible a través de un proxy.',
                     'ar': 'المورد المطلوب متاح فقط عبر وكيل.',
                     'ru': 'Запрошенный ресурс доступен только через прокси.'}},
 '306': {'group': '3xx',
         'title': {'nl': 'Switch Proxy', 'en': 'Switch Proxy', 'zh': '切换代理', 'es': 'Cambiar proxy', 'ar': 'تبديل الوكيل', 'ru': 'Переключить прокси'},
         'meaning': {'nl': 'Wordt niet meer gebruikt.', 'en': 'No longer used.', 'zh': '不再使用。', 'es': 'Ya no se utiliza.', 'ar': 'لم يعد مستخدمًا.', 'ru': 'Больше не используется.'}},
 '307': {'group': '3xx',
         'title': {'nl': 'Tijdelijke omleiding', 'en': 'Temporary Redirect', 'zh': '临时重定向', 'es': 'Redirección temporal', 'ar': 'إعادة توجيه مؤقتة', 'ru': 'Временное перенаправление'},
         'meaning': {'nl': 'Zelfde idee als 302, maar zonder wisselen tussen POST en GET.',
                     'en': 'Same idea as 302, but without switching between POST and GET.',
                     'zh': '与302相同的概念，但不会在POST和GET之间切换。',
                     'es': 'Misma idea que 302, pero sin cambiar entre POST y GET.',
                     'ar': 'نفس فكرة 302، لكن دون التبديل بين POST وGET.',
                     'ru': 'То же, что и 302, но без переключения между POST и GET.'}},
 '308': {'group': '3xx',
         'title': {'nl': 'Permanente omleiding', 'en': 'Permanent Redirect', 'zh': '永久重定向', 'es': 'Redirección permanente', 'ar': 'إعادة توجيه دائمة', 'ru': 'Постоянное перенаправление'},
         'meaning': {'nl': 'Zelfde idee als 301, maar zonder wisselen tussen POST en GET.',
                     'en': 'Same idea as 301, but without switching between POST and GET.',
                     'zh': '与301相同的概念，但不会在POST和GET之间切换。',
                     'es': 'Misma idea que 301, pero sin cambiar entre POST y GET.',
                     'ar': 'نفس فكرة 301، لكن دون التبديل بين POST وGET.',
                     'ru': 'То же, что и 301, но без переключения между POST и GET.'}},
 '400': {'group': '4xx',
         'title': {'nl': 'Bad Request', 'en': 'Bad Request', 'zh': '错误请求', 'es': 'Solicitud incorrecta', 'ar': 'طلب غير صالح', 'ru': 'Неверный запрос'},
         'meaning': {'nl': 'Het verzoek is ongeldig of kan niet goed worden begrepen.',
                     'en': 'The request is invalid or cannot be properly understood.',
                     'zh': '请求无效或无法正确理解。',
                     'es': 'La solicitud no es válida o no puede entenderse correctamente.',
                     'ar': 'الطلب غير صالح أو لا يمكن فهمه بشكل صحيح.',
                     'ru': 'Запрос недействителен или не может быть корректно понят.'}},
 '401': {'group': '4xx',
         'title': {'nl': 'Ongeautoriseerd', 'en': 'Unauthorized', 'zh': '未授权', 'es': 'No autorizado', 'ar': 'غير مصرح', 'ru': 'Не авторизован'},
         'meaning': {'nl': 'De client is niet geauthenticeerd.', 'en': 'The client is not authenticated.', 'zh': '客户端未经身份验证。', 'es': 'El cliente no está autenticado.', 'ar': 'العميل غير موثق.', 'ru': 'Клиент не прошёл аутентификацию.'}},
 '402': {'group': '4xx',
         'title': {'nl': 'Betaling vereist', 'en': 'Payment Required', 'zh': '需要付款', 'es': 'Pago requerido', 'ar': 'الدفع مطلوب', 'ru': 'Требуется оплата'},
         'meaning': {'nl': 'Gereserveerd voor toekomstig gebruik; soms niet-officieel gebruikt.',
                     'en': 'Reserved for future use; sometimes used unofficially.',
                     'zh': '保留供将来使用；有时被非官方使用。',
                     'es': 'Reservado para uso futuro; a veces utilizado de forma no oficial.',
                     'ar': 'محجوز للاستخدام المستقبلي؛ يُستخدم أحيانًا بشكل غير رسمي.',
                     'ru': 'Зарезервировано для будущего использования; иногда используется неофициально.'}},
 '403': {'group': '4xx',
         'title': {'nl': 'Forbidden', 'en': 'Forbidden', 'zh': '禁止访问', 'es': 'Prohibido', 'ar': 'محظور', 'ru': 'Запрещено'},
         'meaning': {'nl': 'De client is bekend, maar heeft geen toegangsrechten.',
                     'en': 'The client is known but does not have access rights.',
                     'zh': '客户端已知，但没有访问权限。',
                     'es': 'El cliente es conocido pero no tiene derechos de acceso.',
                     'ar': 'العميل معروف لكنه لا يملك حقوق الوصول.',
                     'ru': 'Клиент известен, но не имеет прав доступа.'}},
 '404': {'group': '4xx',
         'title': {'nl': 'Niet gevonden', 'en': 'Not Found', 'zh': '未找到', 'es': 'No encontrado', 'ar': 'غير موجود', 'ru': 'Не найдено'},
         'meaning': {'nl': 'De gevraagde resource is niet gevonden.',
                     'en': 'The requested resource could not be found.',
                     'zh': '未找到所请求的资源。',
                     'es': 'No se encontró el recurso solicitado.',
                     'ar': 'لم يتم العثور على المورد المطلوب.',
                     'ru': 'Запрошенный ресурс не найден.'},
         'testing_tips': {'nl': ['Controleer of de URL correct is ingevoerd.',
                                 'Test of de 404-pagina duidelijk uitlegt wat er mis is.',
                                 'Kijk of de gebruiker makkelijk kan navigeren naar andere pagina\'s.',
                                 'Controleer of er kapotte interne links op de site zijn.'],
                          'en': ['Check whether the URL was entered correctly.',
                                 'Test whether the 404 page clearly explains what went wrong.',
                                 'See if the user can easily navigate to other pages.',
                                 'Check whether there are broken internal links on the site.'],
                          'zh': ['检查URL是否输入正确。',
                                 '测试404页面是否清楚地解释了出了什么问题。',
                                 '查看用户是否可以轻松导航到其他页面。',
                                 '检查网站上是否存在损坏的内部链接。'],
                          'es': ['Comprueba si la URL fue ingresada correctamente.',
                                 'Verifica si la página 404 explica claramente qué salió mal.',
                                 'Comprueba si el usuario puede navegar fácilmente a otras páginas.',
                                 'Verifica si hay enlaces internos rotos en el sitio.'],
                          'ar': ['تحقق مما إذا كان عنوان URL قد أدخل بشكل صحيح.',
                                 'اختبر ما إذا كانت صفحة 404 تشرح بوضوح ما حدث من خطأ.',
                                 'انظر إذا كان المستخدم يمكنه التنقل بسهولة إلى صفحات أخرى.',
                                 'تحقق مما إذا كانت هناك روابط داخلية معطوبة على الموقع.'],
                          'ru': ['Проверьте, правильно ли введён URL.',
                                 'Проверьте, ясно ли объясняет страница 404, что пошло не так.',
                                 'Убедитесь, что пользователь может легко перейти на другие страницы.',
                                 'Проверьте, есть ли на сайте неработающие внутренние ссылки.']}},
 '405': {'group': '4xx',
         'title': {'nl': 'Methode niet toegestaan', 'en': 'Method Not Allowed', 'zh': '方法不允许', 'es': 'Método no permitido', 'ar': 'الطريقة غير مسموح بها', 'ru': 'Метод не разрешён'},
         'meaning': {'nl': 'De gebruikte aanvraagmethode wordt niet ondersteund.',
                     'en': 'The request method used is not supported.',
                     'zh': '使用的请求方法不受支持。',
                     'es': 'El método de solicitud utilizado no está soportado.',
                     'ar': 'طريقة الطلب المستخدمة غير مدعومة.',
                     'ru': 'Используемый метод запроса не поддерживается.'}},
 '408': {'group': '4xx',
         'title': {'nl': 'Request Timeout', 'en': 'Request Timeout', 'zh': '请求超时', 'es': 'Tiempo de espera agotado', 'ar': 'انتهت مهلة الطلب', 'ru': 'Тайм-аут запроса'},
         'meaning': {'nl': 'De server heeft te lang gewacht op het verzoek.',
                     'en': 'The server waited too long for the request.',
                     'zh': '服务器等待请求的时间过长。',
                     'es': 'El servidor esperó demasiado tiempo la solicitud.',
                     'ar': 'انتظر الخادم الطلب لفترة طويلة جدًا.',
                     'ru': 'Сервер слишком долго ждал запрос.'}},
 '409': {'group': '4xx',
         'title': {'nl': 'Conflict', 'en': 'Conflict', 'zh': '冲突', 'es': 'Conflicto', 'ar': 'تعارض', 'ru': 'Конфликт'},
         'meaning': {'nl': 'Het verzoek is in conflict met de status van de server.',
                     'en': 'The request conflicts with the current state of the server.',
                     'zh': '请求与服务器的当前状态冲突。',
                     'es': 'La solicitud entra en conflicto con el estado actual del servidor.',
                     'ar': 'الطلب في تعارض مع الحالة الحالية للخادم.',
                     'ru': 'Запрос конфликтует с текущим состоянием сервера.'}},
 '410': {'group': '4xx',
         'title': {'nl': 'Gone', 'en': 'Gone', 'zh': '已删除', 'es': 'Eliminado', 'ar': 'غير متاح نهائيًا', 'ru': 'Удалён'},
         'meaning': {'nl': 'De resource is niet meer beschikbaar en komt niet terug.',
                     'en': 'The resource is no longer available and will not return.',
                     'zh': '资源不再可用，且不会恢复。',
                     'es': 'El recurso ya no está disponible y no volverá.',
                     'ar': 'المورد لم يعد متاحًا ولن يعود.',
                     'ru': 'Ресурс больше недоступен и не вернётся.'}},
 '418': {'group': '4xx',
         'title': {'nl': "I'm a Teapot", 'en': "I'm a Teapot", 'zh': '我是茶壶', 'es': 'Soy una tetera', 'ar': 'أنا إبريق شاي', 'ru': 'Я чайник'},
         'meaning': {'nl': 'Begon als 1-aprilgrap, maar is gestandaardiseerd.',
                     'en': 'Started as an April Fools\' joke but has been standardised.',
                     'zh': '最初是愚人节玩笑，但已被标准化。',
                     'es': 'Comenzó como una broma del Día de los Inocentes pero fue estandarizado.',
                     'ar': 'بدأ كنكتة في أول أبريل لكنه أصبح معيارًا.',
                     'ru': 'Начался как первоапрельская шутка, но был стандартизирован.'}},
 '421': {'group': '4xx',
         'title': {'nl': 'Misdirected Request', 'en': 'Misdirected Request', 'zh': '错误定向请求', 'es': 'Solicitud mal dirigida', 'ar': 'طلب موجّه بشكل خاطئ', 'ru': 'Неверно направленный запрос'},
         'meaning': {'nl': 'De server waarnaar het verzoek is gestuurd kan er niet op reageren.',
                     'en': 'The server to which the request was sent cannot respond to it.',
                     'zh': '接收请求的服务器无法对其做出响应。',
                     'es': 'El servidor al que se envió la solicitud no puede responderla.',
                     'ar': 'الخادم الذي أُرسل إليه الطلب لا يستطيع الاستجابة له.',
                     'ru': 'Сервер, которому был отправлен запрос, не может на него ответить.'}},
 '422': {'group': '4xx',
         'title': {'nl': 'Unprocessable Entity', 'en': 'Unprocessable Entity', 'zh': '无法处理的实体', 'es': 'Entidad no procesable', 'ar': 'كيان غير قابل للمعالجة', 'ru': 'Необрабатываемая сущность'},
         'meaning': {'nl': 'Er zitten semantische fouten in het verzoek.',
                     'en': 'The request contains semantic errors.',
                     'zh': '请求包含语义错误。',
                     'es': 'La solicitud contiene errores semánticos.',
                     'ar': 'يحتوي الطلب على أخطاء دلالية.',
                     'ru': 'Запрос содержит семантические ошибки.'}},
 '423': {'group': '4xx',
         'title': {'nl': 'Vergrendeld', 'en': 'Locked', 'zh': '已锁定', 'es': 'Bloqueado', 'ar': 'مقفل', 'ru': 'Заблокировано'},
         'meaning': {'nl': 'De gevraagde resource is vergrendeld.', 'en': 'The requested resource is locked.', 'zh': '请求的资源已被锁定。', 'es': 'El recurso solicitado está bloqueado.', 'ar': 'المورد المطلوب مقفل.', 'ru': 'Запрошенный ресурс заблокирован.'}},
 '424': {'group': '4xx',
         'title': {'nl': 'Failed Dependency', 'en': 'Failed Dependency', 'zh': '依赖项失败', 'es': 'Dependencia fallida', 'ar': 'فشل التبعية', 'ru': 'Ошибка зависимости'},
         'meaning': {'nl': 'Dit verzoek hangt af van een ander verzoek dat faalde.',
                     'en': 'This request depends on another request that failed.',
                     'zh': '此请求依赖于另一个失败的请求。',
                     'es': 'Esta solicitud depende de otra solicitud que falló.',
                     'ar': 'يعتمد هذا الطلب على طلب آخر فشل.',
                     'ru': 'Этот запрос зависит от другого запроса, который завершился ошибкой.'}},
 '425': {'group': '4xx',
         'title': {'nl': 'Too Early', 'en': 'Too Early', 'zh': '为时过早', 'es': 'Demasiado pronto', 'ar': 'مبكر جدًا', 'ru': 'Слишком рано'},
         'meaning': {'nl': 'De server wil dit verzoek nu nog niet verwerken.',
                     'en': 'The server is not willing to process this request yet.',
                     'zh': '服务器暂时不愿意处理此请求。',
                     'es': 'El servidor no está dispuesto a procesar esta solicitud todavía.',
                     'ar': 'الخادم غير مستعد لمعالجة هذا الطلب في الوقت الحالي.',
                     'ru': 'Сервер не готов обрабатывать этот запрос в данный момент.'}},
 '426': {'group': '4xx',
         'title': {'nl': 'Upgrade vereist', 'en': 'Upgrade Required', 'zh': '需要升级', 'es': 'Actualización requerida', 'ar': 'ترقية مطلوبة', 'ru': 'Требуется обновление'},
         'meaning': {'nl': 'De client moet een nieuwer protocol gebruiken.',
                     'en': 'The client must use a newer protocol.',
                     'zh': '客户端必须使用更新的协议。',
                     'es': 'El cliente debe usar un protocolo más nuevo.',
                     'ar': 'يجب على العميل استخدام بروتوكول أحدث.',
                     'ru': 'Клиент должен использовать более новый протокол.'}},
 '428': {'group': '4xx',
         'title': {'nl': 'Voorwaarde vereist', 'en': 'Precondition Required', 'zh': '需要前提条件', 'es': 'Condición previa requerida', 'ar': 'شرط مسبق مطلوب', 'ru': 'Требуется предусловие'},
         'meaning': {'nl': 'De server eist een voorwaardelijk verzoek.',
                     'en': 'The server requires a conditional request.',
                     'zh': '服务器要求条件请求。',
                     'es': 'El servidor requiere una solicitud condicional.',
                     'ar': 'يشترط الخادم طلبًا مشروطًا.',
                     'ru': 'Сервер требует условного запроса.'}},
 '429': {'group': '4xx',
         'title': {'nl': 'Too Many Requests', 'en': 'Too Many Requests', 'zh': '请求过多', 'es': 'Demasiadas solicitudes', 'ar': 'طلبات كثيرة جدًا', 'ru': 'Слишком много запросов'},
         'meaning': {'nl': 'Er zijn te veel verzoeken in korte tijd gedaan.',
                     'en': 'Too many requests have been made in a short period of time.',
                     'zh': '在短时间内发送了太多请求。',
                     'es': 'Se han realizado demasiadas solicitudes en un corto período de tiempo.',
                     'ar': 'تم تقديم طلبات كثيرة جدًا في فترة زمنية قصيرة.',
                     'ru': 'За короткое время было отправлено слишком много запросов.'},
         'testing_tips': {'nl': ['Controleer na hoeveel verzoeken de limiet wordt bereikt.',
                                 'Test of de foutmelding duidelijk is voor de gebruiker.',
                                 'Kijk of er een wachttijd of retry-informatie wordt gegeven.',
                                 'Controleer of normale gebruikers niet onterecht worden geblokkeerd.'],
                          'en': ['Check after how many requests the limit is reached.',
                                 'Test whether the error message is clear to the user.',
                                 'Check whether a wait time or retry information is provided.',
                                 'Verify that normal users are not incorrectly blocked.'],
                          'zh': ['检查多少请求后会达到限制。',
                                 '测试错误消息对用户是否清晰。',
                                 '检查是否提供了等待时间或重试信息。',
                                 '验证普通用户不会被错误地阻止。'],
                          'es': ['Comprueba tras cuántas solicitudes se alcanza el límite.',
                                 'Verifica si el mensaje de error es claro para el usuario.',
                                 'Comprueba si se proporciona un tiempo de espera o información de reintento.',
                                 'Verifica que los usuarios normales no sean bloqueados incorrectamente.'],
                          'ar': ['تحقق من عدد الطلبات التي يُبلغ فيها الحد.',
                                 'اختبر ما إذا كانت رسالة الخطأ واضحة للمستخدم.',
                                 'تحقق مما إذا كانت هناك معلومات حول وقت الانتظار أو إعادة المحاولة.',
                                 'تأكد من أن المستخدمين العاديين لا يتم حجبهم بشكل غير صحيح.'],
                          'ru': ['Проверьте, после скольких запросов достигается лимит.',
                                 'Проверьте, понятно ли сообщение об ошибке пользователю.',
                                 'Проверьте, предоставляется ли время ожидания или информация о повторной попытке.',
                                 'Убедитесь, что обычные пользователи не блокируются неправомерно.']}},
 '431': {'group': '4xx',
         'title': {'nl': 'Request Header Fields Too Large', 'en': 'Request Header Fields Too Large', 'zh': '请求头字段过大', 'es': 'Campos de encabezado de solicitud demasiado grandes', 'ar': 'حقول رأس الطلب كبيرة جدًا', 'ru': 'Поля заголовка запроса слишком велики'},
         'meaning': {'nl': 'De request headers zijn te groot.', 'en': 'The request headers are too large.', 'zh': '请求头过大。', 'es': 'Las cabeceras de la solicitud son demasiado grandes.', 'ar': 'رؤوس الطلب كبيرة جدًا.', 'ru': 'Заголовки запроса слишком велики.'}},
 '451': {'group': '4xx',
         'title': {'nl': 'Niet beschikbaar om juridische redenen', 'en': 'Unavailable For Legal Reasons', 'zh': '因法律原因不可用', 'es': 'No disponible por razones legales', 'ar': 'غير متاح لأسباب قانونية', 'ru': 'Недоступно по юридическим причинам'},
         'meaning': {'nl': 'De resource is juridisch geblokkeerd.', 'en': 'The resource has been legally blocked.', 'zh': '该资源因法律原因被屏蔽。', 'es': 'El recurso ha sido bloqueado legalmente.', 'ar': 'تم حجب المورد لأسباب قانونية.', 'ru': 'Ресурс заблокирован по юридическим причинам.'}},
 '499': {'group': '4xx',
         'title': {'nl': 'Client Closed Request', 'en': 'Client Closed Request', 'zh': '客户端关闭请求', 'es': 'El cliente cerró la solicitud', 'ar': 'أغلق العميل الطلب', 'ru': 'Клиент закрыл запрос'},
         'meaning': {'nl': 'Niet-officieel gebruik door nginx: client sloot het verzoek voortijdig.',
                     'en': 'Unofficial use by nginx: the client closed the request prematurely.',
                     'zh': 'nginx的非官方用法：客户端提前关闭了请求。',
                     'es': 'Uso no oficial por nginx: el cliente cerró la solicitud prematuramente.',
                     'ar': 'استخدام غير رسمي من قِبل nginx: أغلق العميل الطلب قبل الأوان.',
                     'ru': 'Неофициальное использование nginx: клиент преждевременно закрыл запрос.'}},
 '500': {'group': '5xx',
         'title': {'nl': 'Internal Server Error', 'en': 'Internal Server Error', 'zh': '内部服务器错误', 'es': 'Error interno del servidor', 'ar': 'خطأ داخلي في الخادم', 'ru': 'Внутренняя ошибка сервера'},
         'meaning': {'nl': 'Er is een algemene fout op de server opgetreden.',
                     'en': 'A general error has occurred on the server.',
                     'zh': '服务器发生了一般性错误。',
                     'es': 'Se ha producido un error general en el servidor.',
                     'ar': 'حدث خطأ عام على الخادم.',
                     'ru': 'На сервере произошла общая ошибка.'},
         'testing_tips': {'nl': ['Controleer of de fout reproduceerbaar is.',
                                 'Test welke actie of invoer de fout veroorzaakt.',
                                 'Kijk of de gebruiker een nette foutmelding krijgt.',
                                 'Controleer of de fout zichtbaar is in logs of monitoring.'],
                          'en': ['Check whether the error is reproducible.',
                                 'Test which action or input causes the error.',
                                 'Check whether the user receives a clear error message.',
                                 'Verify whether the error is visible in logs or monitoring.'],
                          'zh': ['检查错误是否可以复现。',
                                 '测试哪个操作或输入导致了错误。',
                                 '检查用户是否收到清晰的错误消息。',
                                 '验证错误是否在日志或监控中可见。'],
                          'es': ['Comprueba si el error es reproducible.',
                                 'Verifica qué acción o entrada provoca el error.',
                                 'Comprueba si el usuario recibe un mensaje de error claro.',
                                 'Verifica si el error es visible en los logs o en el monitoreo.'],
                          'ar': ['تحقق مما إذا كان الخطأ قابلًا للتكرار.',
                                 'اختبر أي إجراء أو مدخل يسبب الخطأ.',
                                 'تحقق مما إذا كان المستخدم يتلقى رسالة خطأ واضحة.',
                                 'تحقق مما إذا كان الخطأ مرئيًا في السجلات أو المراقبة.'],
                          'ru': ['Проверьте, воспроизводится ли ошибка.',
                                 'Проверьте, какое действие или ввод вызывает ошибку.',
                                 'Убедитесь, что пользователь получает понятное сообщение об ошибке.',
                                 'Проверьте, видна ли ошибка в журналах или системе мониторинга.']}},
 '501': {'group': '5xx',
         'title': {'nl': 'Niet geïmplementeerd', 'en': 'Not Implemented', 'zh': '未实现', 'es': 'No implementado', 'ar': 'غير مُنفَّذ', 'ru': 'Не реализовано'},
         'meaning': {'nl': 'De aanvraagmethode wordt niet ondersteund door de server.',
                     'en': 'The request method is not supported by the server.',
                     'zh': '服务器不支持请求方法。',
                     'es': 'El método de solicitud no es compatible con el servidor.',
                     'ar': 'طريقة الطلب غير مدعومة من قِبل الخادم.',
                     'ru': 'Метод запроса не поддерживается сервером.'}},
 '502': {'group': '5xx',
         'title': {'nl': 'Bad Gateway', 'en': 'Bad Gateway', 'zh': '错误网关', 'es': 'Puerta de enlace incorrecta', 'ar': 'بوابة خاطئة', 'ru': 'Плохой шлюз'},
         'meaning': {'nl': 'De server kreeg een slechte respons van een andere server.',
                     'en': 'The server received a bad response from another server.',
                     'zh': '服务器从另一台服务器收到了错误响应。',
                     'es': 'El servidor recibió una respuesta incorrecta de otro servidor.',
                     'ar': 'تلقى الخادم استجابة سيئة من خادم آخر.',
                     'ru': 'Сервер получил неверный ответ от другого сервера.'}},
 '503': {'group': '5xx',
         'title': {'nl': 'Service niet beschikbaar',
                   'en': 'Service Unavailable',
                   'zh': '服务不可用',
                   'es': 'Servicio no disponible',
                   'ar': 'الخدمة غير متاحة',
                   'ru': 'Сервис недоступен'},
         'meaning': {'nl': 'De server is tijdelijk niet beschikbaar.',
                     'en': 'The server is temporarily unavailable.',
                     'zh': '服务器暂时不可用。',
                     'es': 'El servidor no está disponible temporalmente.',
                     'ar': 'الخادم غير متاح مؤقتًا.',
                     'ru': 'Сервер временно недоступен.'},
         'testing_tips': {'nl': ['Controleer of onderhoud duidelijk wordt gecommuniceerd.',
                                 'Test of de service later weer beschikbaar wordt.',
                                 'Kijk of kritieke functies eventueel nog werken.',
                                 'Controleer of monitoring deze situatie goed detecteert.'],
                          'en': ['Check whether maintenance is communicated clearly.',
                                 'Test whether the service becomes available again later.',
                                 'See whether critical functions still remain accessible.',
                                 'Check whether monitoring detects this situation properly.'],
                          'zh': ['检查是否清楚地传达了维护信息。',
                                 '测试服务稍后是否重新可用。',
                                 '查看关键功能是否仍然可访问。',
                                 '检查监控是否正确检测到此情况。'],
                          'es': ['Comprueba si el mantenimiento se comunica claramente.',
                                 'Prueba si el servicio vuelve a estar disponible más tarde.',
                                 'Verifica si las funciones críticas siguen siendo accesibles.',
                                 'Comprueba si el monitoreo detecta esta situación correctamente.'],
                          'ar': ['تحقق مما إذا كانت أعمال الصيانة تُبلَّغ عنها بوضوح.',
                                 'اختبر ما إذا كانت الخدمة ستصبح متاحة مرة أخرى لاحقًا.',
                                 'انظر ما إذا كانت الوظائف الحيوية لا تزال متاحة.',
                                 'تحقق مما إذا كانت المراقبة تكتشف هذا الوضع بشكل صحيح.'],
                          'ru': ['Проверьте, чётко ли сообщается о проведении технического обслуживания.',
                                 'Проверьте, становится ли сервис снова доступным позднее.',
                                 'Убедитесь, что критически важные функции остаются доступными.',
                                 'Проверьте, корректно ли система мониторинга обнаруживает эту ситуацию.']}},
 '504': {'group': '5xx',
         'title': {'nl': 'Gateway Timeout', 'en': 'Gateway Timeout', 'zh': '网关超时', 'es': 'Tiempo de espera de puerta de enlace', 'ar': 'انتهت مهلة البوابة', 'ru': 'Тайм-аут шлюза'},
         'meaning': {'nl': 'De server kreeg niet op tijd antwoord van een andere server.',
                     'en': 'The server did not receive a timely response from another server.',
                     'zh': '服务器未能及时从另一台服务器收到响应。',
                     'es': 'El servidor no recibió una respuesta oportuna de otro servidor.',
                     'ar': 'لم يتلق الخادم استجابة في الوقت المناسب من خادم آخر.',
                     'ru': 'Сервер не получил своевременного ответа от другого сервера.'}},
 '505': {'group': '5xx',
         'title': {'nl': 'HTTP-versie niet ondersteund', 'en': 'HTTP Version Not Supported', 'zh': 'HTTP版本不受支持', 'es': 'Versión HTTP no compatible', 'ar': 'إصدار HTTP غير مدعوم', 'ru': 'Версия HTTP не поддерживается'},
         'meaning': {'nl': 'De HTTP-versie uit het verzoek wordt niet ondersteund.',
                     'en': 'The HTTP version used in the request is not supported.',
                     'zh': '请求中使用的HTTP版本不受支持。',
                     'es': 'La versión HTTP utilizada en la solicitud no es compatible.',
                     'ar': 'إصدار HTTP المستخدم في الطلب غير مدعوم.',
                     'ru': 'Версия HTTP, используемая в запросе, не поддерживается.'}},
 '507': {'group': '5xx',
         'title': {'nl': 'Onvoldoende opslag', 'en': 'Insufficient Storage', 'zh': '存储空间不足', 'es': 'Almacenamiento insuficiente', 'ar': 'مساحة تخزين غير كافية', 'ru': 'Недостаточно места'},
         'meaning': {'nl': 'De server kan niet opslaan wat nodig is om het verzoek te voltooien.',
                     'en': 'The server cannot store what is needed to complete the request.',
                     'zh': '服务器无法存储完成请求所需的内容。',
                     'es': 'El servidor no puede almacenar lo necesario para completar la solicitud.',
                     'ar': 'لا يستطيع الخادم تخزين ما هو ضروري لإتمام الطلب.',
                     'ru': 'Сервер не может сохранить данные, необходимые для выполнения запроса.'}},
 '508': {'group': '5xx',
         'title': {'nl': 'Loop Detected', 'en': 'Loop Detected', 'zh': '检测到循环', 'es': 'Bucle detectado', 'ar': 'تم اكتشاف حلقة', 'ru': 'Обнаружен цикл'},
         'meaning': {'nl': 'De server vond een oneindige lus tijdens verwerking.',
                     'en': 'The server detected an infinite loop while processing.',
                     'zh': '服务器在处理过程中检测到无限循环。',
                     'es': 'El servidor detectó un bucle infinito durante el procesamiento.',
                     'ar': 'اكتشف الخادم حلقة لانهائية أثناء المعالجة.',
                     'ru': 'Сервер обнаружил бесконечный цикл в процессе обработки.'}},
 '511': {'group': '5xx',
         'title': {'nl': 'Netwerkverificatie vereist', 'en': 'Network Authentication Required', 'zh': '需要网络身份验证', 'es': 'Autenticación de red requerida', 'ar': 'مصادقة الشبكة مطلوبة', 'ru': 'Требуется сетевая аутентификация'},
         'meaning': {'nl': 'De client moet authenticeren voordat netwerktoegang wordt toegestaan.',
                     'en': 'The client must authenticate before network access is granted.',
                     'zh': '客户端必须在获得网络访问权限之前进行身份验证。',
                     'es': 'El cliente debe autenticarse antes de que se le conceda acceso a la red.',
                     'ar': 'يجب على العميل المصادقة قبل منح الوصول إلى الشبكة.',
                     'ru': 'Клиент должен пройти аутентификацию, прежде чем ему будет предоставлен доступ к сети.'}},
 '520': {'group': '5xx',
         'title': {'nl': 'Webserver heeft een onbekende fout geretourneerd',
                   'en': 'Web Server Returned an Unknown Error',
                   'zh': 'Web服务器返回未知错误',
                   'es': 'El servidor web devolvió un error desconocido',
                   'ar': 'أعاد خادم الويب خطأً غير معروف',
                   'ru': 'Веб-сервер вернул неизвестную ошибку'},
         'meaning': {'nl': 'Niet-officieel gebruik door Cloudflare.',
                     'en': 'Unofficial use by Cloudflare.',
                     'zh': 'Cloudflare的非官方用法。',
                     'es': 'Uso no oficial por Cloudflare.',
                     'ar': 'استخدام غير رسمي من قِبل Cloudflare.',
                     'ru': 'Неофициальное использование Cloudflare.'}},
 '521': {'group': '5xx',
         'title': {'nl': 'Web Server is niet beschikbaar', 'en': 'Web Server Is Down', 'zh': 'Web服务器宕机', 'es': 'El servidor web está caído', 'ar': 'خادم الويب معطّل', 'ru': 'Веб-сервер недоступен'},
         'meaning': {'nl': 'Niet-officieel gebruik door Cloudflare.',
                     'en': 'Unofficial use by Cloudflare.',
                     'zh': 'Cloudflare的非官方用法。',
                     'es': 'Uso no oficial por Cloudflare.',
                     'ar': 'استخدام غير رسمي من قِبل Cloudflare.',
                     'ru': 'Неофициальное использование Cloudflare.'}},
 '522': {'group': '5xx',
         'title': {'nl': 'Connection Timed Out', 'en': 'Connection Timed Out', 'zh': '连接超时', 'es': 'Tiempo de conexión agotado', 'ar': 'انتهت مهلة الاتصال', 'ru': 'Время соединения истекло'},
         'meaning': {'nl': 'Niet-officieel gebruik door Cloudflare.',
                     'en': 'Unofficial use by Cloudflare.',
                     'zh': 'Cloudflare的非官方用法。',
                     'es': 'Uso no oficial por Cloudflare.',
                     'ar': 'استخدام غير رسمي من قِبل Cloudflare.',
                     'ru': 'Неофициальное использование Cloudflare.'}},
 '523': {'group': '5xx',
         'title': {'nl': 'Origin is onbereikbaar', 'en': 'Origin Is Unreachable', 'zh': '源站不可达', 'es': 'El origen no está disponible', 'ar': 'المصدر غير قابل للوصول', 'ru': 'Источник недоступен'},
         'meaning': {'nl': 'Niet-officieel gebruik door Cloudflare.',
                     'en': 'Unofficial use by Cloudflare.',
                     'zh': 'Cloudflare的非官方用法。',
                     'es': 'Uso no oficial por Cloudflare.',
                     'ar': 'استخدام غير رسمي من قِبل Cloudflare.',
                     'ru': 'Неофициальное использование Cloudflare.'}},
 '524': {'group': '5xx',
         'title': {'nl': 'Er is een time-out opgetreden', 'en': 'A Timeout Occurred', 'zh': '发生超时', 'es': 'Se produjo un tiempo de espera', 'ar': 'حدث انتهاء مهلة', 'ru': 'Произошёл тайм-аут'},
         'meaning': {'nl': 'Niet-officieel gebruik door Cloudflare.',
                     'en': 'Unofficial use by Cloudflare.',
                     'zh': 'Cloudflare的非官方用法。',
                     'es': 'Uso no oficial por Cloudflare.',
                     'ar': 'استخدام غير رسمي من قِبل Cloudflare.',
                     'ru': 'Неофициальное использование Cloudflare.'}},
 '525': {'group': '5xx',
         'title': {'nl': 'SSL-handshake mislukt', 'en': 'SSL Handshake Failed', 'zh': 'SSL握手失败', 'es': 'Error en el protocolo de enlace SSL', 'ar': 'فشل مصافحة SSL', 'ru': 'Ошибка SSL-рукопожатия'},
         'meaning': {'nl': 'Niet-officieel gebruik door Cloudflare.',
                     'en': 'Unofficial use by Cloudflare.',
                     'zh': 'Cloudflare的非官方用法。',
                     'es': 'Uso no oficial por Cloudflare.',
                     'ar': 'استخدام غير رسمي من قِبل Cloudflare.',
                     'ru': 'Неофициальное использование Cloudflare.'}},
 '526': {'group': '5xx',
         'title': {'nl': 'Ongeldig SSL-certificaat', 'en': 'Invalid SSL Certificate', 'zh': 'SSL证书无效', 'es': 'Certificado SSL no válido', 'ar': 'شهادة SSL غير صالحة', 'ru': 'Недействительный SSL-сертификат'},
         'meaning': {'nl': 'Niet-officieel gebruik door Cloudflare.',
                     'en': 'Unofficial use by Cloudflare.',
                     'zh': 'Cloudflare的非官方用法。',
                     'es': 'Uso no oficial por Cloudflare.',
                     'ar': 'استخدام غير رسمي من قِبل Cloudflare.',
                     'ru': 'Неофициальное использование Cloudflare.'}}}
